.github/workflows/lint.yml, mpl_sphinx_theme/__init__.py, setup.cfg
We should try to match Matplotlib in flake8 config. The exceptions in Matplotlib are only for backwards-compatibility with existing code and to avoid mass changes, and this code doesn't require any of them, so all exceptions can be dropped.
~~This depends on #16 and #17, and should not be merged before rebasing.~~
=> Add flake8 CI, and drop exceptions

.gitignore
That is, files that come about due to `pip install -e .`.
=> Ignore editable build files

mpl_sphinx_theme/mpl_nav_bar.html
The Menu bar currently says "Usage Guide", but there is already a "Usage Guide" so I think this should be "User Guide"
=> MNT: change usage->user in the menu bar

docs/conf.py
```
Whilst working on the Reproducible Builds effort [0], I noticed that
mpl-sphinx-theme could not be built reproducibly.
This is because the documentation embedded the current build year. This PR
changes the behaviour of the Sphinx documentation so that it can that
optionally use SOURCE_DATE_EPOCH [1] as the source of this value instead.
I originally filed this in Debian as bug #1005826 [2].
[0] https://reproducible-builds.org/
[1] https://reproducible-builds.org/specs/source-date-epoch/
[2] https://bugs.debian.org/1005826
```
=> Make the documentation build reproducibly

.circleci/config.yml
Currently, doc builds are part of the PR, but then once done, they disappear at whatever rate CircleCI wishes.
This will post the current theme docs on https://matplotlib.org/mpl-sphinx-theme once merged to `main`, following instructions on [the CircleCI blog post](https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/).
=> Add gh-pages deployment

mpl_sphinx_theme/static/css/style.css, mpl_sphinx_theme/theme.conf
and color them a bit more light so that they offset from the page-related buttons theme-switch and search-button.
before:
after:
=> Move external links to the very right of the nav bar

docs/requirements.txt, mpl_sphinx_theme/_version.py, requirements.txt
The changes in #43 require pydata-sphinx-theme >= 0.10.0.  We also did not update the version number here...
=> MNT: update version and pydata-sphinx-theme req

mpl_sphinx_theme/static/css/style.css
Follow up to #43. (attn. @jklymak)
- Coloring follows regular links
- Add margin to the left so that page control buttons are visually separated.
=> Color and margin of nav-bar links

mpl_sphinx_theme/mpl_nav_bar.html
quick fix for #50 by shortening Release Notes to Releases. 
could also maybe make following changes but out of scope 'cause a whole discussion:
Reference -> API 
Plot types -> Plots
and not a shorten but Develop -> Contribute
ETA: This built doc doesn't show the dev dropdown so I can't tell if it fixes the problem. ☹️
=> change release notes to releases

mpl_sphinx_theme/mpl_icon_links.html
This was [reported on twitter](https://twitter.com/OpenTechPark/status/1633536096003842061?t=adEdQHOLzf_-U1UxDpPklQ&s=19): the gitter link in the top navbar returns a 404 - perhaps this is a result of the recent changes at gitter.
=> Fix gitter link in top navbar

mpl_sphinx_theme/__init__.py
For non-main documentation (e.g., `mpl-third-party`), we want the navbar to use absolute links (`https://matplotlib.org/...`) for local development, but when released on the website, it should use `/stable/...` links. This ensures that the navbar links are never broken.
=> Allow setting release-specific navbar link mode

mpl_sphinx_theme/_version.py
- Add compatibility with pydata-sphinx-theme 0.13.0
- Fix broken gitter link in navbar
- Allow setting release-specific navbar link modes
=> Merge tag 3.7.1 into main

LICENSE.txt
Per our meeting discussion, switch the license text to match the metadata in `setup.py`.
Fixes #29
=> Fix license text to be BSD-3-Clause

README.rst
I thought this may be the more appropriate place to document what requirements files need updating upon release of mpl sphinx theme.
There are a couple of other candidates: matplotlib/cheat-sheets and matplotlib/data-prototype, in particular, but those are small enough/not updated enough to bother repinning, I think;
=> Add note to update pins as part of mpl-sphinx-theme release

mpl_sphinx_theme/mpl_nav_bar.html
Way back when, this section of the docs was named contribute. We changed it to develop at some point but that feels too narrow so this restores the name of that section to contribute
=> Change develop in nav bar to contribute

.github/workflows/release.yml
This uses the new Trusted Publisher setup to automatically publish when a release is published.
=> Add a release workflow to publish to PyPI

.github/workflows/release.yml
This seems to cause a conflict when the workflow is triggered by a tag itself: https://github.com/actions/checkout/issues/1467
=> CI: Drop fetch-tags setting from checkout step

mpl_sphinx_theme/mpl_nav_bar.html
Um this is a first pass rather than something I'm strongly attached to, but I'm proposing the following story right to left because it goes from overview of the library to details on demand. I continue to not really know where to place tutorials but the middle kinda makes sense
- plot types -> user guide -> tutorials -> examples -> reference
=> organize navbar in overview->details order

README.rst, mpl_sphinx_theme/_version.py
I will tag off of the `REL: 3.8.0` commit once this is okay.
=> Prepare 3.8.0 release

pyproject.toml
This lead to the logos being missing from the wheels/install
=> SVGs are not in a subfolder

mpl_sphinx_theme/_version.py
Also, bump version to 3.9.0dev0 so that it will continue to be installed correctly on `devdocs` builds, but not in the `v3.8.x` branch.
=> Merge v3.8.x branch up to main

mpl_sphinx_theme/theme.conf
With `pydata-sphinx-theme` 0.14, the default search UI changed to a search box. As noted in https://github.com/matplotlib/mpl-sphinx-theme/issues/80 this breaks the theme look, squashing the top navbar too much.
This PR configures search to be a button again.
=> Always use search icon instead of search box

README.rst
In order to cater for sub-projects that aren't part of the main Matplotlib website (e.g., `cycler`, `pytest-mpl`), this section of the README explains how to override the navbar links to get the default of having the top level table of contents there.
See https://github.com/matplotlib/cycler/pull/99 for an example of this in practice.
Fixes partially https://github.com/matplotlib/mpl-sphinx-theme/issues/47
=> Explain how to override default header links

mpl_sphinx_theme/_version.py
Somewhat like #77, I will tag off of the `REL: 3.9.0` commit once this is okay.
=> Prepare 3.9.0 release

.github/dependabot.yml, .github/workflows/circleci.yml, .github/workflows/lint.yml, .github/workflows/release.yml
Also add dependabot for actions.
=> Update CI workflows to match main repo

docs/conf.py, mpl_sphinx_theme/donate_sidebar.html, mpl_sphinx_theme/static/css/style.css, pyproject.toml
This improves the layout of the donate button by stretching it to fill the full width of the sidebar. In order to test this I've also added the current donate button sidebar from https://github.com/matplotlib/matplotlib. This adds a dependency of `sphinx-design` here. I've done this in the spirit of keeping all the code for the donate button in `mpl-sphinx-theme`, so it can be used by other projects, not just the main Matplotlib docs.
In conjunction with https://github.com/matplotlib/matplotlib/pull/29789, this improves the layout:
Before:
After:
=> Improvements to LH sidebar layout

.circleci/config.yml, .github/dependabot.yml, .vscode/settings.json, pyproject.toml
Currently to get a consistent look across all the Matplotlib website repositories requires pinning `pydata-sphinx-theme` in each repository. To prevent having to do that, this PR pins `pydata-sphinx-theme` here, and adds dependabot configuration to automatically update this as new versions come out.
To start with I've pinned at 0.15.4 because this is what version `matplotlib/matplotlib` is on, and it will also test that dependabot is working (it should try to update to 0.16.x).
=> Pin exact version of pydata-sphinx-theme

mpl_sphinx_theme/static/css/style.css
Since pydata-sphinx-theme is not making progress with reasonably displaying lot of content in the nav bar on medium-width screens, let's put the relatively simple workaround from
https://github.com/pydata/pydata-sphinx-theme/pull/2117 into the mpl-sphinx-theme.
before:
after:
=> Reduce height of nav bar when items don't fit in one line
